### ISSUE TITLE
Iframe is dead

### ISSUE THREAD

**Issue by corneadoug** [NFLabs/zeppelin#204]
I ran into that problem today,
the Iframe link is showing an empty page (I also tried with a new note in case)

I'm currently investigating, it seems it is not related to asIframe css since loading the paragraph without asIframe options doesn't work either (empty content inside the paragraph)

I'm following 2 tracks for this bug:
- Check the Context and that the query send data
- Check the route and that the route parameters are used correctly

**Comment by bzz** [comment]
Does IFrame work now?

**Comment by corneadoug** [comment]
I can try it again, but that bug was supposed to be fix in #203

**Comment by corneadoug** [comment]
It was fixed, I close the issue
