### ISSUE TITLE
Need scrollable dropdown

### ISSUE THREAD

**Issue by swkimme** [NFLabs/zeppelin#232]
Guys, 
Cause I'm working with Zeppelin everyday, I got so many notebooks  and I found I cannot access the notebook on the bottom.

I tried simple css
.dropdown-menu {
    max-height: 200px;
    height: auto;
    overflow-x: hidden;
}

and result is below:
![screen shot 2014-12-04 at 10 32 20 am](https://cloud.githubusercontent.com/assets/5210115/5292132/ea6bf1e2-7ba0-11e4-8d64-75f3755847d4.png)

but the design is not looking good for me. 
Is anyone there who can redesign the scrollbar?

**Comment by minahlee** [comment]
This issue is resolved in #286

**Comment by swkimme** [comment]
Cool!
