### ISSUE TITLE
No Data available Message on Graph after some time idle

### ISSUE THREAD

**Issue by corneadoug** [NFLabs/zeppelin#239]
I've been using Zeppelin around today on the booth, and I get this message "No Data Available" on some graphs after some time. Even if I refresh it and it regraph the result again, the message often pop again after a few seconds/minutes.

Also, when the message is shown, If I switch to table mode I can see that there is data, but when I come back on the graph, it is blank with the message on it. (only refresh the query can show the graph again)

Anybody had the same issue?

**Comment by bzz** [comment]
Is this still an issue or we may close this one for now?

**Comment by corneadoug** [comment]
We can close it for now, since I never got the problem after

**Comment by bzz** [comment]
then +1 for closing it

On Thu, Jan 22, 2015 at 10:33 AM, CORNEAU Damien <notifications@github.com>
wrote:

> We can close it for now, since I never got the problem after
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NFLabs/zeppelin/issues/239#issuecomment-70956767>.
>



-- 
--
Kind regards,
Alexander.
