### ISSUE TITLE
Build fail with Spark 1.2.0

### ISSUE THREAD

**Issue by swkimme** [NFLabs/zeppelin#260]
When I build Zeppelin with spark 1.2.0, it fails 

[ERROR] Failed to execute goal on project zeppelin-spark: Could not resolve dependencies for project com.nflabs.zeppelin:zeppelin-spark:jar:0.5.0-SNAPSHOT: Failure to find org.apache.spark:spark-repl_2.10:jar:1.2.0 in https://raw.github.com/NFLabs/mvn-repo/master/releases was cached in the local repository, resolution will not be reattempted until the update interval of nflabs public repository has elapsed or updates are forced -> [Help 1]

found that spark-repl 1.2.0 is not on maven repository, as a workaround I tried build with spark-repl 1.1.1 and I guess it's not working correctly.

**Comment by Leemoonsoo** [comment]
working on #294

**Comment by swkimme** [comment]
Close this issue since there are open PR for this issue.
