### ISSUE TITLE
Run interpreter in separate process.

### ISSUE THREAD

**Issue by Leemoonsoo** [NFLabs/zeppelin#278]
Currently, Zeppelin interpreter is running with it's own classloader for prividing sandbox like environment to avoid interfere with other interpreters.

But still, stdout/stderr will be interfere among all interpreters while they're running in the same JVM process. And some library who hardcoded to use Application classloader instead of Threadcontext loader won't work in this way.

It'll be good if Zeppelin have option `fork mode` for each interpreter and this options runs interpreter in separate process.

**Comment by Leemoonsoo** [comment]
I'm thinking thrift for RPC between Zeppelin and Interpreter process. are there better alternatives?

**Comment by bzz** [comment]
Let's think carefully here, as this is kind of big shift.
Or is it something super-simple? may be I'm missing the point then.

Have you i.e seen https://issues.apache.org/jira/browse/SPARK-4605 ?

What kind of protocol do you have in mind?
Implementation details less important here (thrift vs protobuf, etc), at
least for me.

May be we should discuss this in dev@ ML to get more exposure and feedback
over this proposal, what do you think?


On Tue, Jan 13, 2015 at 2:12 PM, Lee moon soo <notifications@github.com>
wrote:

> I'm thinking thrift for RPC between Zeppelin and Interpreter process. are
> there better alternatives?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NFLabs/zeppelin/issues/278#issuecomment-69696494>.
>



-- 
--
Kind regards,
Alexander.

**Comment by Leemoonsoo** [comment]
For example, Zeppelin currently wraps Interpreter instance to add some additional feature. Here's how Zeppelin calls interpreter function

```
[Zeppelin ---> (LazyOpenInterpreter (ClassLoaderInterpreter (SparkInterpreter)))]
```

My idea was just add wrappers and make them communicate via some kind RPC mechanism.

```
[zeppelin-server ---> (LazyOpenInterpreter (RemoteInterpreter))] ----RPC-----> [(RemoteInterpreterServer (SparkInterpreter))]
```

LazyOpenInterpreter, ClassLoaderInterpreter, SparkInterpreter, they all inherits Interpreter class.
So i was thinking inserting RemoteInterpreter, RemoteInterpreterServer class and make them call using RPC mechanisms. that hides all the complexities from zeppelin-server. So it's simple any protocol does not matter if they can used for RPC.

It's very good to know about https://issues.apache.org/jira/browse/SPARK-4605.

I think i can put some more detail and then i can start one discussion thread in dev mailing list.
Thanks for the feedback!

**Comment by bzz** [comment]
Discussion moved to http://s.apache.org/zeppelin-multiprocess

**Comment by Leemoonsoo** [comment]
Closing this issue while #364 is merged.
