### ISSUE TITLE
Add support for HiveContext

### ISSUE THREAD

**Issue by btiernay** [NFLabs/zeppelin#287]
Currently only `SQLContext` is supported. Since `HiveContext` offers the superset of operations, and is already available on the classpath, it seems appropriate to expose this to users to be able to interact with datasets in the Hive metastore.

**Comment by felixcheung** [comment]
Some (most?) Hadoop distributions do not have the build of Spark jar with Hive
http://spark.apache.org/docs/latest/sql-programming-guide.html#hive-tables
"Spark SQL also supports reading and writing data stored in Apache Hive. However, since Hive has a large number of dependencies, it is not included in the default Spark assembly. Hive support is enabled by adding the -Phive and -Phive-thriftserver flags to Spark’s build. This command builds a new assembly jar that includes Hive"

Would that be a problem?

**Comment by btiernay** [comment]
As it turns out, it is already on the classpath. Also, Hive is already supported it seems

**Comment by btiernay** [comment]
Example:

```scala
import org.apache.spark.sql.hive.HiveContext

val hc = new HiveContext(z.sc)
val rdd = hc.sql(""SELECT 1 as x").cache()
val q = z.sqlContext.applySchema(rdd,rdd.schema)
q.registerTempTable("t")
```

```sql
%sql
SELECT * from t
```

**Comment by felixcheung** [comment]
Cool.
This requires spark-hive in the classpath right?
I don't have it there but I think it's cool. They (Michael Armbrust) say HiveContext is the superset and we should all use it..

**Comment by Leemoonsoo** [comment]
I created small improvements at #306. 
The idea is basically let user configure what kind of context (HiveContext vs SQLContext) `%sql` is going to use. 

@btiernay suggested way still uses SQLContext when it queries with `%sql`.
Will it help this issue? or is there better way to handle it?

**Comment by btiernay** [comment]
I like what you've done. Much better. Mine was just showing how it was possible but very awkward.  Thanks!

**Comment by swkimme** [comment]
I guess this issue is nicely handled by #306 , let's close this one.

**Comment by sudhir9p** [comment]
Its working fine in Zapplien , I have been writing in Scala IDE, when I tried loading or creating hive tables using HiveContext, it's creating or searching locally in metastore_db , wven though I placed   hive-site.xml in Spark conf folder and even in my class path , How to make my application to pick from hive-site.xml metastore 

I tried:
objHiveContext.setConf("hive.metastore.warehouse.dir", "hdfs://ServerIP:HiveportNum/apps/hive/warehouse")

Can anyone help on this???

**Comment by Leemoonsoo** [comment]
@sudhir9p This github repository is no longer in use. see https://github.com/NFLabs/zeppelin/blob/master/README.md

If you're writing spark application in your ide, you can try include hive-site.xml in your application's classpath.
