### ISSUE TITLE
Blank page when starting

### ISSUE THREAD

**Issue by felixcheung** [NFLabs/zeppelin#297]
I started zeppelin and opened browser to point to localhost:8080, but there is only a blank page. Any idea?

$ ./bin/zeppelin-daemon.sh start
Log dir doesn't exist, create /home//zeppelin/zeppelin-0.5.0-SNAPSHOT/logs
Pid dir doesn't exist, create /home//zeppelin/zeppelin-0.5.0-SNAPSHOT/run
Notbook dir doesn't exist, create /home//zeppelin/zeppelin-0.5.0-SNAPSHOT/notebook
Zeppelin start                                                    [  OK  ]

In logs:
 INFO [2015-01-23 13:26:08,225] ({main} WebInfConfiguration.java[unpack]:478) - Extract jar:file:/home//zeppelin/zeppelin-0.5.0-SNAPSHOT/zeppelin-web-0.5.0-SNAPSHOT.war!/ to /tmp/jetty-0.0.0.0-8080-zeppelin-web-0.5.0-SNAPSHOT.war-_-any-/webapp
 INFO [2015-01-23 13:26:08,565] ({main} StandardDescriptorProcessor.java[visitServlet]:284) - NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
 INFO [2015-01-23 13:26:10,046] ({main} StandardDescriptorProcessor.java[visitServlet]:284) - NO JSP Support for /docs, did not find org.apache.jasper.servlet.JspServlet
 INFO [2015-01-23 13:26:10,065] ({main} AbstractConnector.java[doStart]:338) - Started SocketConnector@0.0.0.0:8080
 INFO [2015-01-23 13:26:10,065] ({main} ZeppelinServer.java[main]:83) - Started

INFO: Scanning for root resource and provider classes in the packages:
  com.nflabs.zeppelin.rest
  com.wordnik.swagger.jersey.listing
Jan 23, 2015 1:26:08 PM com.sun.jersey.api.core.ScanningResourceConfig logClasses
INFO: Root resource classes found:
  class com.nflabs.zeppelin.rest.NotebookRestApi
  class com.nflabs.zeppelin.rest.ZeppelinRestApi
  class com.nflabs.zeppelin.rest.InterpreterRestApi
  class com.wordnik.swagger.jersey.listing.ApiListingResourceJSON
Jan 23, 2015 1:26:08 PM com.sun.jersey.api.core.ScanningResourceConfig logClasses
INFO: Provider classes found:
  class com.wordnik.swagger.jersey.listing.JerseyResourceListingProvider
  class com.wordnik.swagger.jersey.listing.JerseyApiDeclarationProvider
Jan 23, 2015 1:26:08 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.9 09/02/2011 11:17 AM'
Jan 23, 2015 1:26:08 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Adding the following classes declared in META-INF/services/jersey-server-components to the resource configuration:
  class org.atmosphere.jersey.AtmosphereResourceConfigurator
Jan 23, 2015 1:26:10 PM com.sun.jersey.spi.inject.Errors processErrorMessages
WARNING: The following warnings have been detected with resource and/or provider classes:
  WARNING: A HTTP GET method, public javax.ws.rs.core.Response com.nflabs.zeppelin.rest.InterpreterRestApi.listInterpreter(java.lang.String), should not consume any entity.

**Comment by corneadoug** [comment]
Hi Felix,
The best method for a white page or web related error when the web is running is to open the developer tool of your web browser (F12) and check the console for error messages

**Comment by felixcheung** [comment]
Great, thanks for tip.
Below is the error. I've noticed that conf/ does not have a zeppelin-site.xml (only the template), does it have to be created manually there?

[16:03:07.858] [$injector:modulerr] Failed to instantiate module zeppelinWebApp due to:
WebSocket is not defined
("ws://localhost:8081")@http://localhost:8080/scripts/vendor.js:11
([object Object],[object Object])@http://localhost:8080/scripts/scripts.js:1
e((function (a, b) {"use strict";b.prefix("").uri(getWebsocketProtocol() + "://" + location.hostname + ":" + getPort()), a.when("/", {templateUrl: "views/main.html"}).when("/notebook/:noteId", {templateUrl: "views/notebooks.html", controller: "NotebookCtrl"}).when("/notebook/:noteId/paragraph/:paragraphId?", {templateUrl: "views/notebooks.html", controller: "NotebookCtrl"}).when("/interpreter", {templateUrl: "views/interpreter.html", controller: "InterpreterCtrl"}).otherwise({redirectTo: "/"});}))@http://localhost:8080/scripts/vendor.js:4
d([object Array])@http://localhost:8080/scripts/vendor.js:4
("zeppelinWebApp",2,[object Array])@http://localhost:8080/scripts/vendor.js:4
f([object Array],(function (a) {"use strict";
function d(a) {var b, c;for (b = 0, c = a.length; c > b; b++) {var d = a[b], e = A.get(d[0]);e[d[1]].apply(e, d[2]);}}

if (!y.get(a)) {y.put(a, true);try {u(a) ? (b = ae(a), c = c.concat(n(b.requires)).concat(b._runBlocks), d(b._invokeQueue), d(b._configBlocks)) : x(a) ? c.push(A.invoke(a)) : je(a) ? c.push(A.invoke(a)) : fb(a, "module");} catch (e) {throw je(a) && (a = a[a.length - 1]), e.message && e.stack && -1 == e.stack.indexOf(e.message) && (e = e.message + "\n" + e.stack), Re("modulerr", "Failed to instantiate module {0} due to:\n{1}", a, e.stack || e.message || e);}}}))@http://localhost:8080/scripts/vendor.js:3
n([object Array])@http://localhost:8080/scripts/vendor.js:4
Sb([object Array],false)@http://localhost:8080/scripts/vendor.js:4
()@http://localhost:8080/scripts/vendor.js:3
_([object Object],[object Array],[object Object])@http://localhost:8080/scripts/vendor.js:3
$([object HTMLDocument],_)@http://localhost:8080/scripts/vendor.js:3
((function (a, b) {return new _.fn.init(a, b);}))@http://localhost:8080/scripts/vendor.js:7
([object Array])@http://localhost:8080/scripts/vendor.js:2
([object HTMLDocument],[object Array])@http://localhost:8080/scripts/vendor.js:2
()@http://localhost:8080/scripts/vendor.js:2
g([object Event])@http://localhost:8080/scripts/vendor.js:1

http://errors.angularjs.org/1.3.8/$injector/modulerr?p0=zeppelinWebApp&p1=WebSocket%20is%20not%20defined%0A(%22ws%3A%2F%2Flocalhost%3A8081%22)%40http%3A%2F%2Flocalhost%3A8080%2Fscripts%2Fvendor.js%3A11%0A(%5Bobject%20Object%5D%2C%5Bobject%20Object%5D)%40http%3A%2F%2Flocalhost%3A8080%2Fscripts%2Fscripts.js%3A1%0Ae((function%20(a%2C%20b)%20%7B%22use%20strict%22%3Bb.prefix(%22%22).uri(getWebsocketProtocol()%20%2B%20%22%3A%2F%2F%22%20%2B%20location.hostname%20%2B%20%22%3A%22%20%2B%20getPort())%2C%20a.when(%22%2F%22%2C%20%7BtemplateUrl%3A%20%22views%2Fmain.html%22%7D).when(%22%2Fnotebook%2F%3AnoteId%22%2C%20%7BtemplateUrl%3A%20%22views%2Fnotebooks.html%22%2C%20controller%3A%20%22NotebookCtrl%22%7D).when(%22%2Fnotebook%2F%3AnoteId%2Fparagraph%2F%3AparagraphId%3F%22%2C%20%7BtemplateUrl%3A%20%22views%2Fnotebooks.html%22%2C%20controller%3A%20%22NotebookCtrl%22%7D).when(%22%2Finterpreter%22%2C%20%7BtemplateUrl%3A%20%22views%2Finterpreter.html%22%2C%20controller%3A%20%22InterpreterCtrl%22%7D).otherwise(%7BredirectTo%3A%20%22%2F%22%7D)%3B%7D))%40http%3A%2F%2Flocalhost%3A8080%2Fscripts%2Fvendor.js%3A4%0Ad(%5Bobject%20Array%5D)%40http%3A%2F%2Flocalhost%3A8080%2Fscripts%2Fvendor.js%3A4%0A(%22zeppelinWebApp%22%2C2%2C%5Bobject%20Array%5D)%40http%3A%2F%2Flocalhost%3A8080%2Fscripts%2Fvendor.js%3A4%0Af(%5Bobject%20Array%5D%2C(function%20(a)%20%7B%22use%20strict%22%3B%0Afunction%20d(a)%20%7Bvar%20b%2C%20c%3Bfor%20(b%20%3D%200%2C%20c%20%3D%20a.length%3B%20c%20%3E%20b%3B%20b%2B%2B)%20%7Bvar%20d%20%3D%20a%5Bb%5D%2C%20e%20%3D%20A.get(d%5B0%5D)%3Be%5Bd%5B1%5D%5D.apply(e%2C%20d%5B2%5D)%3B%7D%7D%0A%0Aif%20(!y.get(a))%20%7By.put(a%2C%20true)%3Btry%20%7Bu(a)%20%3F%20(b%20%3D%20ae(a)%2C%20c%20%3D%20c.concat(n(b.requires)).concat(b._runBlocks)%2C%20d(b._invokeQueue)%2C%20d(b._configBlocks))%20%3A%20x(a)%20%3F%20c.push(A.invoke(a))%20%3A%20je(a)%20%3F%20c.push(A.invoke(a))%20%3A%20fb(a%2C%20%22module%22)%3B%7D%20catch%20(e)%20%7Bthrow%20je(a)%20%26%26%20(a%20%3D%20a%5Ba.length%20-%201%5D)%2C%20e.message%20%26%26%20e.stack%20%26%26%20-1%20%3D%3D%20e.stack.indexOf(e.message)%20%26%26%20(e%20%3D%20e.message%20%2B%20%22%5Cn%22%20%2B%20e.stack)%2C%20Re(%22modulerr%22%2C%20%22Failed%20to%20instantiate%20module%20%7B0%7D%20due%20to%3A%5Cn%7B1%7D%22%2C%20a%2C%20e.stack%20%7C%7C%20e.message%20%7C%7C%20e)%3B%7D%7D%7D))%40http%3A%2F%2Flocalhost%3A8080%2Fscripts%2Fvendor.js%3A3%0An(%5Bobject%20Array%5D)%40http%3A%2F%2Flocalhost%3A8080%2Fscripts%2Fvendor.js%3A4%0ASb(%5Bobject%20Array%5D%2Cfalse)%40http%3A%2F%2Flocalhost%3A8080%2Fscripts%2Fvendor.js%3A4%0A()%40http%3A%2F%2Flocalhost%3A8080%2Fscripts%2Fvendor.js%3A3%0A_(%5Bobject%20Object%5D%2C%5Bobject%20Array%5D%2C%5Bobject%20Object%5D)%40http%3A%2F%2Flocalhost%3A8080%2Fscripts%2Fvendor.js%3A3%0A%24(%5Bobject%20HTMLDocument%5D%2C_)%40http%3A%2F%2Flocalhost%3A8080%2Fscripts%2Fvendor.js%3A3%0A((function%20(a%2C%20b)%20%7Breturn%20new%20_.fn.init(a%2C%20b)%3B%7D))%40http%3A%2F%2Flocalhost%3A8080%2Fscripts%2Fvendor.js%3A7%0A(%5Bobject%20Array%5D)%40http%3A%2F%2Flocalhost%3A8080%2Fscripts%2Fvendor.js%3A2%0A(%5Bobject%20HTMLDocument%5D%2C%5Bobject%20Array%5D)%40http%3A%2F%2Flocalhost%3A8080%2Fscripts%2Fvendor.js%3A2%0A()%40http%3A%2F%2Flocalhost%3A8080%2Fscripts%2Fvendor.js%3A2%0Ag(%5Bobject%20Event%5D)%40http%3A%2F%2Flocalhost%3A8080%2Fscripts%2Fvendor.js%3A1%0A @ http://localhost:8080/scripts/vendor.js:3

**Comment by felixcheung** [comment]
This is because of Firefox 10.x
http://stackoverflow.com/questions/9688900/websocket-html5-referenceerror-websocket-is-not-defined
