### ISSUE TITLE
Support yarn-client mode

### ISSUE THREAD

**Issue by jongyoul** [NFLabs/zeppelin#312]
I'm doing fix to support yarn-client.

I've founded we need to add spark-yarn dependency and more...

My goal is that we run zeppelin in a yarn cluster without setting anything except `yarn-site.xml`

**Comment by felixcheung** [comment]
Shouldn't it be able to read yarn-site from YARN_CONF_DIR? That's how most of spark script works.
I have also been trying to get this to work on and off for weeks (as you remember...) let me know if there is anything I can help with. Thanks

**Comment by jongyoul** [comment]
@felixcheung I've added spark-yarn dependency but couldn't work with another error. I'll dig start-up code for spark on yarn-client mode. I think there is no jar to launch to yarn container.

**Comment by swkimme** [comment]
I guess most major contributor in Zeppelin has lack of experience with Yarn
cluster, so it would be BIG help if you guys can contribut to the way
runing Zeppelin on Yarn or Mesos.
Cheers!

**Comment by felixcheung** [comment]
I am having problem pulling dependencies after adding spark-yarn to pom. Do you have a commit or a branch? That would really help me to move forward.

--- Original Message ---

**Comment by felixcheung** [comment]
@jongyoul ?
Here's what I have:
- added spark-yarn in dependency in pom
Here's what I see:
- package not found errors for a bunch of hadoop-* 
- not sure why zeppelin is not referencing maven common / sonatype. Added that and it is still not working

[WARNING] The POM for org.apache.hadoop:hadoop-yarn-api:jar:1.0.4 is missing, no dependency information available
[WARNING] The POM for org.apache.hadoop:hadoop-yarn-common:jar:1.0.4 is missing, no dependency information available
[WARNING] The POM for org.apache.hadoop:hadoop-yarn-server-web-proxy:jar:1.0.4 is missing, no dependency information available
[WARNING] The POM for org.apache.hadoop:hadoop-yarn-client:jar:1.0.4 is missing, no dependency information available

**Comment by jongyoul** [comment]
@felixcheung I've found a complicated solution for running zeppelin under a yarn cluster. See my pull request. #352

**Comment by jongyoul** [comment]
@felixcheung I've changed for building zeppelin correctly. new build option is {{-Pyarn}}

**Comment by jongyoul** [comment]
@felixcheung Hi, I've finished my PR #352 .
My build script is
```
JAVA_HOME=`/usr/libexec/java_home -v 1.7` mvn -Phadoop-2.4 -Dhadoop.version=2.5.2 -Pspark-1.2 -Pyarn clean package -DskipTests
```
My configuration in zeppelin-env.sh is
```
export SPARK_YARN_JAR="/Users/jl/local/src/g/apache-spark/dist/lib/spark-assembly-1.2.1-hadoop2.5.2.jar"
export HADOOP_HOME="/usr/local/Cellar/hadoop/2.5.2/libexec"
```

**Comment by jongyoul** [comment]
We can close this PR.

**Comment by yongjiaw** [comment]
how to set number of executors and executor memory? ZEPPELIN_JAVA_OPTS="-Dspark.executor.memory=32g" doesn't work, the executor memory is still the default 512m. For num-executors, it is a YARN property.

**Comment by jongyoul** [comment]
Which version do you use? If you use remote interpreter version, you can
this environment value in a zeppelin-env.sh

On Thu, Mar 26, 2015 at 12:40 PM, yongjiaw <notifications@github.com> wrote:

> how to set number of executors and executor memory?
> ZEPPELIN_JAVA_OPTS="-Dspark.executor.memory=32g" doesn't work, the executor
> memory is still the default 512m. For num-executors, it is a YARN property.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NFLabs/zeppelin/issues/312#issuecomment-86325496>.
>



-- 
이종열, Jongyoul Lee, 李宗烈
http://madeng.net

**Comment by yongjiaw** [comment]
I'm just running by calling start-zeppelin.sh, something like 
ZEPPELIN_PORT=9998 ZEPPELIN_JAVA_OPTS="-Dspark.executor.memory=32g" SPARK_YARN_JAR=../spark/assembly/target/scala-2.10/spark-assembly-1.3.1-SNAPSHOT-hadoop2.5.2.jar HADOOP_CONF_DIR=/etc/hadoop/conf HADOOP_USER_NAME=hdfs ./bin/zeppelin-daemon.sh start
This way SparkContext is probably within the same process.
"executor-memory" is a SparkConf property, while "num-executor" is set in System property to pass to YARN by looking at SparkSubmit.scala. 
What I did is I can set executor-memory inside Zeppelin's interpreter page, and restart the interpreter there, but then I at Spark's UI for the restarted SparkContext, I still got 512M memory, even the spark.executor.memory property is 32G under the Environment page.

**Comment by jongyoul** [comment]
If you use current master, You should your environment variables into conf/zeppelin-env.sh because interpreter.sh reads this file for configuring remoteInterpreter. Or, check your interpreter page on the web ui. this variable affects sparkContext. I've tested with spark.executor.memory=32g, I've found Executor memory is 16.6GB and driver memory is 530.0MB in executors page of spark web.

**Comment by yongjiaw** [comment]
oh, I see. I'm actually in local mode. what other env variable do I need to set to actually run with yarn

**Comment by jongyoul** [comment]
@yongjiaw Ok, I see. And Zeppelin moves its infra to ASF, so you can make a jira ticket if you judge some bugs or use mailing list, too. It's more effiecient way to makes some contributors help you.

**Comment by yongjiaw** [comment]
It all works now after I looked at the zeppelin log and figured out it's a version compatibility issue. 16.6GB appears to be the max allowed executor memory for Spark, while I don't see that in any documentation. Anyways, Zeppelin is wonderful. I think it's the best Spark UI publicly available right now :)

**Comment by jongyoul** [comment]
@yongjiaw You can find a hint from codes of `BlockManager`
