### ISSUE TITLE
Build fails on zeppelin-web

### ISSUE THREAD

**Issue by biggedi** [NFLabs/zeppelin#320]
Hey guys,

first of all: great project you are working on. Looks for me like the most promising GUI for Spark.

My problem: I'm trying to build Zeppelin (freshly cloned from master) on Ubuntu 14.04, but it fails persistently on building the web-application:

[INFO] bower jquery#>= 1.9.0                   validate 2.1.3 against git://github.com/jquery/jquery.git#>= 1.9.0
[INFO] bower angular#1.3.8                      ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/angular/bower-angular.git", exit code of #128
[INFO] 
[INFO] Additional error details:
[INFO] fatal: unable to connect to github.com:
[INFO] github.com[0: 192.30.252.129]: errno=Connection timed out
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:32.831s
[INFO] Finished at: Thu Feb 05 11:35:38 CET 2015
[INFO] Final Memory: 7M/240M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.20:bower (bower install) on project zeppelin-web: Failed to run task: 'bower --allow-root install' failed. (error code 1) -> [Help 1]

I already did "./bower cache clean" in zeppelin-web subdirectory and removed folders "zeppelin-web/node" and "zeppelin-web/node_module" prior building

Tried building with:
mvn clean package
mvn clean package -DskipTests -Dspark.version=1.1.1 -Dhadoop.version=2.4.0

It sounds like a simple timeout, but re-running the build fails at the same point again.

Best regards,
Benjamin

**Comment by biggedi** [comment]
I found the hint to switch github from git:// to https://, but currently it still produces an error:

[INFO] bower json3#~3.3.1                       ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/bestiejs/json3.git", exit code of #128
[INFO] 
[INFO] Additional error details:
[INFO] fatal: unable to access 'https://github.com/bestiejs/json3.git/': Failed to connect to github.com port 443: Connection timed out

**Comment by anthonycorbacho** [comment]
Hi, please read this read me https://github.com/NFLabs/zeppelin/blob/master/zeppelin-web/README.md

**Comment by biggedi** [comment]
Although changing to https, it still doesn't work. However, I'm certain this is an issue of my company network, as building on a similar Ubuntu machine in a different network works just fine.

So, sorry for bugging you with this and Go Zeppelin!

**Comment by drorata** [comment]
```git config --global url."https://".insteadOf git://``` solved the issue for me as well.
