### ISSUE TITLE
error output font

### ISSUE THREAD

**Issue by cdfhuang** [NFLabs/zeppelin#323]
If there is an error message, the current font causes the caret to be visually misaligned with the column of the error. The space characters in this font have a different width than other characters. Here is an example.

![misaligned](https://cloud.githubusercontent.com/assets/10159056/6086183/9f1775b4-adf4-11e4-966c-0e71497f872c.PNG)

**Comment by swkimme** [comment]
STRONGLY agree with you. 
I've also created an issue for that, 
https://github.com/NFLabs/zeppelin/issues/222

Can you recommend some fixed-width font for output??

**Comment by swkimme** [comment]
I've created a PR, changed the output as the same font with editor.
(actually, i just restore commented css)

https://github.com/NFLabs/zeppelin/pull/327

![screen shot 2015-02-07 at 1 27 10 pm](https://cloud.githubusercontent.com/assets/5210115/6090836/dfc86f44-aecd-11e4-9890-264038cabf04.png)

Now it just looks good and also goes well with space-formatted outputs.

**Comment by swkimme** [comment]
Thanks for raising issue!

**Comment by cdfhuang** [comment]
Thanks for providing a fix faster than I can respond!

**Comment by swkimme** [comment]
Even I've almost forgot that issue I've created..
Raising an issue is always welcomed & desirable even there was a duplicated one!
