### ISSUE TITLE
Web build fail

### ISSUE THREAD

**Issue by swkimme** [NFLabs/zeppelin#348]
I'm helping Spark community members to install Zeppelin, 
2 of them get failed building zeppelin-web. 

![10997053_778633538879986_1339924033_n](https://cloud.githubusercontent.com/assets/5210115/6189500/76fd8f6a-b3de-11e4-8551-312cdb7c58b3.jpg)

**Comment by swkimme** [comment]
https://github.com/NFLabs/zeppelin/issues/293 is one of them

**Comment by corneadoug** [comment]
Usually in the zeppelin-web folder there is a bower_components folder, I
guess thats what the error mean. I think the mvn package is supposed to
create it

**Comment by swkimme** [comment]
Yes, I found bower_components dir has not created for them,
Don't know why yet.

**Comment by healongee** [comment]
I solved that problem. i got the solution form this web page.
https://github.com/NFLabs/zeppelin/blob/master/zeppelin-web/README.md
1. install git
2. $ git config --global url."https://".insteadOf git://
3. $ mvn install -DskipTests
zeppelin web application installed successfully.
