### ISSUE TITLE
Package Zeppelin to DEB

### ISSUE THREAD

**Issue by jongyoul** [NFLabs/zeppelin#369]
I'm trying to make a maven profile for packaging debian package of Zeppelin. I'll update a simple design document more details.

**Comment by jongyoul** [comment]
In generally, a debian package is installed under /usr/share, thus I think that It's good to follow this structure for Zeppelin, and also to make a symbolic link to conserve Zeppelin's structure like standalone mode.

```
# zeppelin-env.sh
export ZEPPELIN_INSTALL_DIR=/usr/share/zeppelin
export ZEPPELIN_HOME=${ZEPPELIN_INSTALL_DIR}
export ZEPPELIN_CONF=/etc/zeppelin
export ZEPPELIN_LOG_DIR=/var/log/zeppelin
export ZEPPELIN_PID_DIR=/var/run/zeppelin
export ZEPPELIN_NOTEBOOK_DIR=/var/lib/zeppelin
```

```
# Symbolic links
${ZEPPELIN_HOME}/conf -> ${ZEPPELIN_CONF}
${ZEPPELIN_HOME}/logs -> ${ZEPPELIN_LOG_DIR}
${ZEPPELIN_HOME}/run -> ${ZEPPELIN_PID_DIR}
${ZEPPELIN_HOME}/notebook -> ${ZEPPELIN_NOTEBOOK_DIR}
```

**Comment by Leemoonsoo** [comment]
Looks nice. Either _zeppelind_ looks fine for init script name. (Or just _zeppelin_ ?)

**Comment by anthonycorbacho** [comment]
@moon https://github.com/NFLabs/zeppelin/pull/171#issuecomment-69881954

**Comment by Leemoonsoo** [comment]
@anthonycorbacho I think there is difference between script under ZEPPELIN_HOME/bin/ and script under /etc/init.d/

**Comment by jongyoul** [comment]
@Leemoonsoo I almost fix this issue. Please review my PR #371.

**Comment by youngwookim** [comment]
Guys, I'm afraid it's too late to join this discussion. I believe that packaging individual project is useful for users. Integration into *stacks* is much useful in real world as well :-) Apache Bigtop aims for that! If you interested in this, I would like to join the effort.

**Comment by jongyoul** [comment]
@youngwookim Hi, Apache Bigtop is already issued on #371 by @bzz. I'm not good at Apache Bigtop, but It looks so much interesting. I know you would be better than me at Bigtop, but I want to make codes for Bigtop by myself. Could you help me if I have some troubles? Thank you so much for your interests.

**Comment by youngwookim** [comment]
@jongyoul Sounds good to me! Once Zeppelin rely on ASF infra, I would start discussion on this. Thanks!

**Comment by jongyoul** [comment]
@youngwookim Thanks to agree on my opinion. If Zeppelin moves to ASF infra, Please help me make a patch for adopting to Apache Bigtop.

**Comment by youngwookim** [comment]
@jongyoul OK. If you need any help or discussion, feel free to ping me! Let's chat some time when we are both free it would be good to discuss interesting topics.

**Comment by jongyoul** [comment]
This issue is resolved and I will handle some issues argued in this issue as new issues.
