### ISSUE TITLE
sqlc -> sqlContext?

### ISSUE THREAD

**Issue by swkimme** [NFLabs/zeppelin#386]
Now Spark shell initialize sqlContext as it starts, 
it would be better if we match the variable name with Spark.

https://github.com/apache/spark/commit/3d3ecd77411bfdd1c72be51616c46a6caf839be2

**Comment by Leemoonsoo** [comment]
#384 creates variable 'sqlContext', too. (as well as 'sqlc')

**Comment by swkimme** [comment]
Oh I didn't know that. Great!
