### ISSUE TITLE
Dependency loading not working, if loaded packages are imported directly after

### ISSUE THREAD

**Issue by biggedi** [NFLabs/zeppelin#395]
Hey guys,

on the current master I got some problems with the dependency loader. I'm importing some code from an external jar.

For doing so, I'm loading a jar from the local maven repository in one paragraph and in the next paragraph I'm importing the package in it.

However, there are some weird problems: If I start execution of the second paragraph before the first paragraph is finished (or if I use "Run all paragraphs"), the just loaded jar ist not yet available and importing the packages fails.

If I, however, wait for like 2 seconds after the first paragraph finished, importing the classes works just fine.

In an older build (as of 2646c4d826a6b7547c07391b7bea656b023f769f) everything still worked fine. I'm running Spark 1.2.1 and the error both appears in local and Standalone cluster mode.
Maybe this is connected to 9a083d00af1ace455dd1492d122f23ca01cc39a4, which appear to me as the only major change on dependency loading from my last stable version.

First paragraph:
```
%dep

z.reset()
z.reset("thesis:ZeppelinExtensions:0.0.1-SNAPSHOT")
```

Second paragraph
```
import thesis._
// The main package is called thesis
```
```
<console>:17 error: not found: value thesis
         import thesis._
                ^
```

I know this is a weird one, but maybe someone knows an obvious reason.

All the best and thanks for your awesome work!

**Comment by biggedi** [comment]
Adding a question to this: Is it possible to automate such dependency loading and imports somehow?

**Comment by Leemoonsoo** [comment]
Hi, biggedi. 
Thanks for reporting a problem and using Zeppelin.

Currently, master branch has a known problem that paragraph run order is not preserved. ie. 'Run all paragraphs' suppose to run one by one from first to last but order is not preserved when it submit job to a remote interpreter process. I think the problem comes with #374 and i'm working on it.

And about second question, could you explain little bit more about 'automate'? do you mean bringing dependency when Zeppelin is starting?

**Comment by biggedi** [comment]
Thank you for the quick answer! That pretty much explains my problems.

About the second question: I got one "setup"-notebook, in which dependencies are loaded as well as a number of datasources loaded and pre-processed. Currently, after starting Zeppelin, I manually run this notebook before any analysis is starting.

I would appreciate a possibility to either mark certain notebooks to be run on startup or have a different option to have some code executed on startup.

All the best!
PS: Zeppelin is really awesome, I'm currently using it in my thesis :-)

**Comment by Leemoonsoo** [comment]
I think a feature 'run on startup' is totally reasonable to have. 
Thanks for suggesting a good feature!

**Comment by Leemoonsoo** [comment]
You can try this patch. #397

**Comment by biggedi** [comment]
This patch solves my issue, thanks!
