### ISSUE TITLE
Zeppelin: web Application .......................... FAILURE

### ISSUE THREAD

**Issue by saptaksen** [NFLabs/zeppelin#419]
[INFO] Copying slf4j-api-1.7.10.jar to /root/incubator-zeppelin/tajo/target/../../interpreter/tajo/slf4j-api-1.7.10.jar
[INFO]
[INFO] --- maven-dependency-plugin:2.8:copy (copy-artifact) @ zeppelin-tajo ---
[INFO] Configured Artifact: org.apache.zeppelin:zeppelin-tajo:0.5.0-incubating-SNAPSHOT:jar
[INFO] Copying zeppelin-tajo-0.5.0-incubating-SNAPSHOT.jar to /root/incubator-zeppelin/tajo/target/../../interpreter/tajo/zeppelin-tajo-0.5.0-incubating-SNAPSHOT.jar
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Zeppelin: web Application 0.5.0-incubating-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ zeppelin-web ---
[INFO] Deleting /root/incubator-zeppelin/zeppelin-web/target
[INFO]
[INFO] --- maven-checkstyle-plugin:2.13:checkstyle (checkstyle) @ zeppelin-web ---
[INFO]
[INFO] --- maven-checkstyle-plugin:2.13:check (checkstyle) @ zeppelin-web ---
[INFO]
[INFO]
[INFO] --- maven-resources-plugin:2.7:copy-resources (copy-resources) @ zeppelin-web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 17 resources
[INFO]
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-maven) @ zeppelin-web ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce) @ zeppelin-web ---
[INFO]
[INFO] --- frontend-maven-plugin:0.0.23:install-node-and-npm (install node and npm) @ zeppelin-web ---
[INFO] Node v0.10.18 is already installed.
[INFO] Found NPM version 1.3.8
[INFO]
[INFO] --- frontend-maven-plugin:0.0.23:npm (npm install) @ zeppelin-web ---
[INFO] Running 'npm install --color=false' in /root/incubator-zeppelin/zeppelin-web
[INFO]
[INFO] --- frontend-maven-plugin:0.0.23:bower (bower install) @ zeppelin-web ---
[INFO] Running 'bower --allow-root install' in /root/incubator-zeppelin/zeppelin-web
[ERROR]
[ERROR] module.js:340
[ERROR]     throw err;
[ERROR]           ^
[ERROR] Error: Cannot find module 'q'
[ERROR]     at Function.Module._resolveFilename (module.js:338:15)
[ERROR]     at Function.Module._load (module.js:280:25)
[ERROR]     at Module.require (module.js:364:17)
[ERROR]     at require (module.js:380:17)
[ERROR]     at Object.<anonymous> (/root/incubator-zeppelin/zeppelin-web/node_modules/bower/bin/bower:6:9)
[ERROR]     at Module._compile (module.js:456:26)
[ERROR]     at Object.Module._extensions..js (module.js:474:10)
[ERROR]     at Module.load (module.js:356:32)
[ERROR]     at Function.Module._load (module.js:312:12)
[ERROR]     at Function.Module.runMain (module.js:497:10)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Zeppelin ........................................... SUCCESS [  5.024 s]
[INFO] Zeppelin: Interpreter .............................. SUCCESS [ 21.092 s]
[INFO] Zeppelin: Zengine .................................. SUCCESS [ 12.294 s]
[INFO] Zeppelin: Spark .................................... SUCCESS [ 37.086 s]
[INFO] Zeppelin: Markdown interpreter ..................... SUCCESS [  6.526 s]
[INFO] Zeppelin: Angular interpreter ...................... SUCCESS [  3.367 s]
[INFO] Zeppelin: Shell interpreter ........................ SUCCESS [  3.540 s]
[INFO] Zeppelin: Hive interpreter ......................... SUCCESS [  5.545 s]
[INFO] Zeppelin: Tajo interpreter ......................... SUCCESS [  4.179 s]
[INFO] Zeppelin: web Application .......................... FAILURE [  1.224 s]
[INFO] Zeppelin: Server ................................... SKIPPED
[INFO] Zeppelin: Packaging distribution ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:40 min
[INFO] Finished at: 2015-06-01T04:19:47+00:00
[INFO] Final Memory: 78M/861M
[INFO] ------------------------------------------------------------------------

**Comment by bzz** [comment]
Thank you for your interest! 

Zeppelin has now migrated to Apache, so in case of any further questions it's better to email appropriate mailing list i.e users@zeppelin.incubator.apache.org
