### ISSUE TITLE
Why has a letter '#' end of url:?

### ISSUE THREAD

**Issue by Anne623** [NFLabs/zeppelin#420]
Hi，I find  zeppelin url is 
'''http://xx.xxx.xxx.xxx:8080/#/''' 
or  '''http://xx.xxx.xxx.xxx:8080/#/notebook/notebook_id''', 

Always has a letter '#' inside url, may i replace my word like 'zeppelin' or delete it?  As below:
 '''http://xx.xxx.xxx.xxx:8080/'''  and '''http://xx.xxx.xxx.xxx:8080/notebook/notebook_id'''
or 
 '''http://xx.xxx.xxx.xxx:8080/zeppelin/'''  and '''http://xx.xxx.xxx.xxx:8080/zeppelin/notebook/notebook_id'''

**Comment by corneadoug** [comment]
Hi,
This repository is Deprecated, Zeppelin moved to Apache Repository.
You can find it there: https://github.com/apache/incubator-zeppelin
