### ISSUE TITLE
Spark-sql "no such table ..."

### ISSUE THREAD

**Issue by OuesFa** [NFLabs/zeppelin#425]
Hello everybody !

I'm trying to use Spark and Zeppelin to import and visulize datas from Elasticsearch. (Spark 1.5, ES-Hadoop connector 2.1).

In the first Paragraph of the notebook, i import datas from my Elasticsearch Index with Spark Sql then i convert it to a DF and i use _registerTempTable_ on it, it seems to work fine, the paragraph executes without error.

However, when i try to use spark sql in the second paragraph : 
* %sql SELECT * FROM myTable
it doesn't work, i have an exception
_org.apache.spark.sql.AnalysisException: no such table myTable ; line 1 pos 14_

Any idea to solve this issue please ?
Thank you

**Comment by bzz** [comment]
Hi, Zeppelin has moved to Apache and this repository, as stated in description, is not active.

The best place to ask for help would be user@ mailing list from http://zeppelin.incubator.apache.org/community.html there you can also find a link to JIRA issue tracker.

It would be great if you could post your question there and close this issue.

Thanks!

**Comment by OuesFa** [comment]
Thank you so much.
